DATA_PATH = "./data/alex2"
CAMERAS_PATH = f"{DATA_PATH}/cameras_attributes.npz"
DEPTHS_PATH = f"{DATA_PATH}/depth"
RAYS_PATH = f"{DATA_PATH}/rays"

FOV = 60
DEPTHMAP_SIZE_RESCALE = 100/1920
TARGET_IMAGE_SIZE = [100, 100]

# BASE DATASET STRUCTURE
BASE_CAMERA_RAYS_ENTRY = "ray_maps"
BASE_CAMERA_TRANSFORM_ENTRY = "cameras_matrices"
BASE_CAMERA_PROJECTION_ENTRY = "projection_matrices"

# TARGET DATASET STRUCTURE
DEPTH_MAP_ENTRY = "depth_map"
RAY_DIRECTIONS_ENTRY = "ray_directions"
CAMERA_TRANSFORM_ENTRY = "camera_transform"
CAMERA_PROJECTION_ENTRY = "camera_projection"

# AFTER POST PROCESS
FILTERED_DEPTH_MAP_ENTRY = "filtered_depth_map"
FILTERED_RAY_DIRECTIONS_ENTRY = "filtered_ray_directions"

# SAVE SYSTEM
CHECKPOINT_NAME = "checkpoint.pth"